theme: jekyll-theme-minimal
title: Soundy
logo: https://github.com/syfds/soundy/blob/master/data/icons/128/com.github.syfds.soundy.svg
github.is_project_page: true
github.public: true
github.repository_url: https://github.com/syfds/soundy
github.zip_url: https://github.com/syfds/soundy/releases/download